name: generate_test_app
description: "Image Generator Test App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  injectable: ^2.4.2
  get_it: ^9.0.5
  go_router: ^17.0.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.9.1
  build_runner: ^2.10.4
  freezed: ^3.2.3
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
